### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by ddervosj** [capt-meelo/MassMap#2]
Hello,

I am unable to run Massmap, receiving below errors when scanning a list of IPs from file:

Starting masscan 1.0.6 (http://bit.ly/14GZzcT) at 2019-10-03 09:44:42 GMT
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 17 hosts [65535 ports/host]
rm: cannot remove '/home/xxx/Downloads/MassMap/paused.conf': No such file or directory
/home/xxx/Downloads/MassMap/results/masscan.xml:1: parser error : Document is empty

^
unable to parse /home/xxx/Downloads/MassMap/results/masscan.xml
[*] Masscan Done! View the HTML report at /home/xxx/Downloads/MassMap/results
[+] Running Nmap.
Starting Nmap 7.80 ( https://nmap.org ) at 2019-10-03 12:44 EEST
Error #486: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!
compilation error: file /home/xxx/Downloads/MassMap/results/nmap.xml line 1 element nmaprun
xsltParseStylesheetProcess : document is not a stylesheet
[*] Nmap Done! View the HTML reports at /home/xxx/Downloads/MassMap/results

Any idea why is this happening?

**Comment by Sholway** [comment]
> Hello,
> 
> I am unable to run Massmap, receiving below errors when scanning a list of IPs from file:
> 
> Starting masscan 1.0.6 (http://bit.ly/14GZzcT) at 2019-10-03 09:44:42 GMT
> -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
> Initiating SYN Stealth Scan
> Scanning 17 hosts [65535 ports/host]
> rm: cannot remove '/home/xxx/Downloads/MassMap/paused.conf': No such file or directory
> /home/xxx/Downloads/MassMap/results/masscan.xml:1: parser error : Document is empty
> 
> ^
> unable to parse /home/xxx/Downloads/MassMap/results/masscan.xml
> [_] Masscan Done! View the HTML report at /home/xxx/Downloads/MassMap/results [+] Running Nmap. Starting Nmap 7.80 ( https://nmap.org ) at 2019-10-03 12:44 EEST Error #486: Your port specifications are illegal. Example of proper form: "-100,200-1024,T:3000-4000,U:60000-" QUITTING! compilation error: file /home/xxx/Downloads/MassMap/results/nmap.xml line 1 element nmaprun xsltParseStylesheetProcess : document is not a stylesheet [_] Nmap Done! View the HTML reports at /home/xxx/Downloads/MassMap/results
> 
> Any idea why is this happening?




i have the same error,i solved this problem.
you didn't have results directory ,so just run these command blow:
#cd MassMap &&mkdir results
then you can run.
